# Generated by Django 5.2.6 on 2026-05-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, default='', max_length=20, verbose_name='cédula')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('grado', models.CharField(choices=[('1RO', '1ro Secundaria'), ('2DO', '2do Secundaria'), ('3RO', '3ro Secundaria'), ('4TO', '4to Secundaria'), ('5TO', '5to Secundaria'), ('6TO', '6to Secundaria')], max_length=10)),
                ('seccion', models.CharField(blank=True, default='A', max_length=5, verbose_name='sección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'estudiantes',
                'ordering': ['grado', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('CONDUCTA', 'Conducta'), ('PARTICIPACION', 'Participación'), ('LOGRO', 'Logro'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'observación',
                'verbose_name_plural': 'observaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materias', models.ManyToManyField(blank=True, related_name='profesores', to='core.materia')),
            ],
            options={
                'verbose_name_plural': 'profesores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='core.profesor'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tardanza'), ('E', 'Excusa')], default='P', max_length=1)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.estudiante')),
            ],
            options={
                'verbose_name_plural': 'asistencias',
                'ordering': ['-fecha', 'estudiante__apellido'],
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
