# Generated by Django 6.0.5 on 2026-05-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_observacion_materia_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='visible_padre',
            field=models.BooleanField(default=False, help_text='Si está marcado, el contenido podrá verse en el currículum familiar.', verbose_name='visible para padres/tutores'),
        ),
    ]
