# Generated by Django 6.0.5 on 2026-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_notas_planificacion_p1p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='valor',
            field=models.PositiveSmallIntegerField(default=1, help_text='Valor del 1 al 5 según la importancia del registro.', verbose_name='puntos'),
        ),
    ]
