# Generated by Django 6.0.5 on 2026-05-14 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_observacion_visible_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='core.profesor')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TareaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETO', 'Completo'), ('NECESITA_MEJORA', 'Necesita mejora'), ('NO_REALIZADO', 'No realizado')], default='PENDIENTE', max_length=20)),
                ('tardio', models.BooleanField(default=False)),
                ('comentario_maestro', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_tarea_editadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tarea', to='core.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'evaluación de tarea',
                'verbose_name_plural': 'evaluaciones de tarea',
                'ordering': ['estudiante__apellido', 'estudiante__nombre'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='TareaGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('1RO', '1ro Secundaria'), ('2DO', '2do Secundaria'), ('3RO', '3ro Secundaria'), ('4TO', '4to Secundaria'), ('5TO', '5to Secundaria'), ('6TO', '6to Secundaria')], max_length=10)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'grado asignado',
                'verbose_name_plural': 'grados asignados',
                'unique_together': {('tarea', 'grado')},
            },
        ),
    ]
