# Generated by Django 6.0.5 on 2026-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='modalidad',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('ESCRITA', 'Escrita')], default='ESCRITA', max_length=10),
        ),
        migrations.AddField(
            model_name='tareaevaluacion',
            name='puntaje',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Oral: 1–5. Escrita: 1–10.', null=True, verbose_name='puntaje'),
        ),
    ]
