# Generated by Django 6.0.5 on 2026-05-27 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participacion_origen'),
        ('tareas', '0004_remove_tareagrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='core.materia', verbose_name='materia'),
        ),
    ]
