# Generated by Django 6.0.5 on 2026-05-14 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_observacion_visible_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudNuevoEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_estudiante', models.CharField(max_length=32)),
                ('nombre_solicitante', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'solicitud de nuevo enlace',
                'verbose_name_plural': 'solicitudes de nuevo enlace',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_padre', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'invitación padre',
                'verbose_name_plural': 'invitaciones padre',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='padres', to='core.estudiante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padre_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'padre / tutor',
                'verbose_name_plural': 'padres / tutores',
            },
        ),
        migrations.CreateModel(
            name='ProfesorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.profesor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil profesor',
                'verbose_name_plural': 'perfiles profesor',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROFESOR', 'Profesor'), ('PADRE', 'Padre / Tutor'), ('ESTUDIANTE', 'Estudiante')], default='PADRE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
